// Re-export from centralized icons
export {
  HomeIcon,
  SubscriptionIcon,
  WalletIcon,
  UsersIcon,
  ChatIcon,
  UserIcon,
  LogoutIcon,
  SunIcon,
  MoonIcon,
  MenuIcon,
  CloseIcon,
  GamepadIcon,
  ClipboardIcon,
  InfoIcon,
  CogIcon,
  WheelIcon,
  GiftIcon,
  SearchIcon,
  PlusIcon,
  ArrowRightIcon,
  DownloadIcon,
  PaletteIcon,
  // Подключить-таб glyph (P0 connect slice — hi-fi §1.1).
  PowerIcon,
  RocketIcon,
} from '../../icons';
